# Generated by Django 4.2.17 on 2025-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_voter_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='matric_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
