# Generated by Django 4.2.17 on 2025-01-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_voter_matric_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.position'),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('matric_number', 'voted_position')},
        ),
    ]
