# Generated by Django 4.2.17 on 2025-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voter_voted_position_alter_voter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voted_position',
        ),
        migrations.AddField(
            model_name='voter',
            name='voted_position',
            field=models.ManyToManyField(blank=True, to='voting.position'),
        ),
    ]
